name: Build and Deploy
on: 
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_STAVA_ATHELTE_ID: ${{ secrets.SECRET_STAVA_ATHELTE_ID }}
          envkey_SECRET_STRAVA_ACCESS_TOKEN: ${{ secrets.SECRET_STRAVA_ACCESS_TOKEN }}
          envkey_SECRET_STRAVA_CLIENT_ID: ${{ secrets.SECRET_STRAVA_CLIENT_ID }}
          envkey_SECRET_STRAVA_CLIENT_SECRET: ${{ secrets.SECRET_STRAVA_CLIENT_SECRET }}
          envkey_SECRET_STRAVA_REFRESH_TOKEN: ${{ secrets.SECRET_STRAVA_REFRESH_TOKEN }}

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy.
